### ISSUE TITLE
NIMROD review.

### ISSUE THREAD

**Issue by rodrigogrow** [rodrigogrow/GameHistoryTimeline#1]
NIMROD:

 Observações:

1) Precisa mudar JSON para o novo formato.
2) Precisa enriquecer o resumo (Deve ter informações como inovações, mecânica do jogo, plataforma para o qual foi desenvolvido e curiosidades).
3) Aumentar o contéudo do full_text (Deve ter o  máximo de informações possíveis sobre o jogo - depois iremos montar o HTML em conjunto).
4) Adicionar link de gameplay
5) Adicionar link de demonstração se possível
6) Adicionar +2 imagens no campo "images" (escolham as imagens iremos adicionar na próxima aula).

**Comment by vinics12** [comment]
Descrição da main_image corrigida
