### ISSUE TITLE
Lunar Lander

### ISSUE THREAD

**Issue by rodrigogrow** [rodrigogrow/GameHistoryTimeline#16]
1) Melhorar texto do resumo (Deve ter informações como inovações, mecânica do jogo, plataforma para o qual foi desenvolvido e curiosidades).
2) Add descrição de todas as imagens

**Comment by tsantosfigueira** [comment]
#16 Descrições Adicionadas e imagens repetidas "removidas"

**Comment by tsantosfigueira** [comment]
#16 Reformulado o resumo

**Comment by rodrigogrow** [comment]
Valeu Thiago! Ficou muito bom :)

**Comment by tsantosfigueira** [comment]
Valeu Professor!

**Comment by rodrigogrow** [comment]
Só uma coisa coloca o demo antigo tbm!! ele tava bem legal :)
