### ISSUE TITLE
Pong review.

### ISSUE THREAD

**Issue by rodrigogrow** [rodrigogrow/GameHistoryTimeline#5]
1) Precisa mudar JSON para o novo formato.
2) Corrigir data
3) Corrigir Headline
4) Precisa enriquecer o resumo (Deve ter informações como inovações, mecânica do jogo, plataforma para o qual foi desenvolvido e curiosidades).
5) Aumentar o contéudo do full_text (Deve ter o  máximo de informações possíveis sobre o jogo - depois iremos montar o HTML em conjunto).
6) Adicionar link de gameplay
7) Adicionar link de demonstração se possível
8) Adicionar +2 imagens no campo "images" (escolham as imagens iremos adicionar na próxima aula).

**Comment by tsantosfigueira** [comment]
Link Slide Share para adicionar ao Pong: http://pt.slideshare.net/TSantosFigueira/pong-the-game

**Comment by rodrigogrow** [comment]
Slides adicionado :)
