### ISSUE TITLE
Lunar Lander review.

### ISSUE THREAD

**Issue by rodrigogrow** [rodrigogrow/GameHistoryTimeline#6]
1) Precisa mudar JSON para o novo formato.
2) Adicionar os criadores.
3) Corrigir Data
4) Corrigir Headline
5) Precisa enriquecer o resumo (Deve ter informações como inovações, mecânica do jogo, plataforma para o qual foi desenvolvido e curiosidades).
6) Aumentar o contéudo do full_text (Deve ter o  máximo de informações possíveis sobre o jogo - depois iremos montar o HTML em conjunto).
7) Adicionar link de gameplay
8) Adicionar link de demonstração se possível
9) Adicionar +2 imagens no campo "images" (escolham as imagens iremos adicionar na próxima aula).

**Comment by tsantosfigueira** [comment]
link Slide Share para os slides do Lunar Lander: http://pt.slideshare.net/TSantosFigueira/lunar-lander-the-game

**Comment by rodrigogrow** [comment]
Já adicionei os slides :)
Valeu!
